# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66be0e26f77f2019cdd3d8f5f162d864c4b620ceb90db1fd918a02e1259de5b8eaa0a4d43b66efc8e374530aa1261e7a299216d60cc1c05aa1b8d9987744d6a7

test:
  secret_key_base: b66678a3cdf488ba3e2a75f63d3b06064458256cb9049fb15a19c1a22f171819f721e6729e23e166dc0fe4af322be154d4f47616d663711dd10c0b26379d47b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
